language: python

# http://docs.travis-ci.com/user/languages/python/
python:
 - 3.4

# http://docs.travis-ci.com/user/multi-os/
os:
 - osx
 - linux

install:
 - pip install --upgrade -q pip
 - pip install --upgrade -q ciscoconfparse


script: make test

matrix:
  allow_failures:
    # - python: 3.5
    # - python: 3.6