language: python

# http://docs.travis-ci.com/user/languages/python/
python:
 - 3.2
 - 3.3
 - 3.4
 - 3.5

# http://docs.travis-ci.com/user/multi-os/
os:
 - linux

install:
 - pip install pybuilder
 - pip install xlrd

script: pyb

matrix:
  allow_failures:
    # - python: 3.5